version: "3"

services:

  shopware:
    image: dockware/dev:6.6.1.0  # or specify a specific version
    container_name: shopware04
    ports:
      - "80:80"
      - "3306:3306"
      - "22:22"
      - "8888:8888"
      - "9999:9999"
      - "9998:9998"
    volumes:
      - "shop04_volume:/var/www/html"
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=1 

volumes:
  shop04_volume:
    driver: local

networks:
  web:
    external: false